### ISSUE TITLE
Image issues with Link select/Location/Person

### ISSUE THREAD

**Issue by tadghh** [rghv234/mini.cur#1]
All of the hand icons have what look like artifacts at the bottom right (visible on chrome sites like Wikipedia). 

![unknown](https://user-images.githubusercontent.com/47073445/110544053-c2954180-80f0-11eb-8e77-4361d3649e93.png)

**Comment by rghv234** [comment]
Hello, thanks for reaching out, I fixed the problem now, it must've been caused by a bug in the software I used to make the cursors
